### GET ALL NOTES

GET http://localhost:3001/api/notes


### GET SINGLE NOTE
GET http://localhost:3001/api/notes/62e972a967dfa1fa34722a16


### CREATE A NOTE 
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbTEyMyIsImlkIjoiNjJlOWY0NTc2NTc3NjFlNTM1OWZjNjFlIiwiaWF0IjoxNjU5Njc2MjQxLCJleHAiOjE2NTk2Nzk4NDF9.LLDks4e4lfuO4_wkZV6RQo27IWuD-TQ7Sx3Ln5q4vzg

{
    "title": "created note using tokenExtractor middleware",
    "body": "some body goes here"
}


### UPDATE SINGLE NOTE 
PUT http://localhost:3001/api/notes/62eca662d883b7969b8c8a76
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbTEyMyIsImlkIjoiNjJlOWY0NTc2NTc3NjFlNTM1OWZjNjFlIiwiaWF0IjoxNjU5Njc3MjgwLCJleHAiOjE2NTk2ODA4ODB9._t0eMTd8S-JW8GpqIMtxbLeeyJVWzK2jgAKCL1qiS5Q

{
    "title": "updated note return orignal: false -sam123",
    "body": "updated the body"
}


### DELETE SINGLE NOTE
DELETE http://localhost:3001/api/notes/62eadadadcaea7bf7d472820
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbTEyMyIsImlkIjoiNjJlOWY0NTc2NTc3NjFlNTM1OWZjNjFlIiwiaWF0IjoxNjU5Njc3MjgwLCJleHAiOjE2NTk2ODA4ODB9._t0eMTd8S-JW8GpqIMtxbLeeyJVWzK2jgAKCL1qiS5Q

### ==== USERS ====

### GET ALL USERS
GET http://localhost:3001/api/users

### GET SINGLE USER
GET http://localhost:3001/api/users/62e9ec55316ef62e4caf26f2

### CREATE A USER
POST http://localhost:3001/api/users 
Content-Type: application/json

{
    "username": "sam123",
    "name": "sam test",
    "password": "helloworld"
}

### UPDATE A USER
PUT http://localhost:3001/api/users/62e9ec55316ef62e4caf26f2
Content-Type: application/json 

{
    "username": "devtest2",
    "name": "Bob Bob",
    "password": "password"
}


### DELETE A USER
DELETE http://localhost:3001/api/users/


### ==== AUTH ROUTES ====
POST http://localhost:3001/auth/login
Content-Type: application/json 

{
    "username": "sam123",
    "password": "helloworld"
}